version: '3.12'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      # - MYSQL_RANDOM_ROOT_PASSWORD
      # - MYSQL_ALLOW_EMPTY_PASSWORD
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
